apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-casson-reverse-proxy
  labels:
    service: udagram-casson-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-casson-reverse-proxy
  template:
    metadata:
      labels:
        app: udagram-casson-reverse-proxy
    spec:
      containers:
      - image: cassonchris/udagram-casson-reverse-proxy
        name: udagram-casson-reverse-proxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always