language: minimal

services: docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl

install:
  - docker-compose -f docker/docker-compose-build.yaml build --parallel

after_success:
  - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  - docker tag udagram-casson-api-feed cassonchris/udagram-casson-api-feed:latest
  - docker tag udagram-casson-api-user cassonchris/udagram-casson-api-user:latest
  - docker tag udagram-casson-frontend cassonchris/udagram-casson-frontend:latest
  - docker tag udagram-casson-reverse-proxy cassonchris/udagram-casson-reverse-proxy:latest
  - docker push cassonchris/udagram-casson-api-feed
  - docker push cassonchris/udagram-casson-api-user
  - docker push cassonchris/udagram-casson-frontend
  - docker push cassonchris/udagram-casson-reverse-proxy
