language: node_js
node_js:
  - 13

branches:
  only:
    - master

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udacity-c3-restapi-feed .
  - docker tag udacity-c3-restapi-feed cassonchris/udacity-c3-restapi-feed:latest

after_success:
  - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push cassonchris/udacity-c3-restapi-feed