language: node_js
node_js:
  - 13

branches:
  only:
    - master

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-casson-api-feed udagram-casson-api-feed
  - docker tag udagram-casson-api-feed cassonchris/udagram-casson-api-feed:latest
  - docker build -t udagram-casson-api-user udagram-casson-api-user
  - docker tag udagram-casson-api-user cassonchris/udagram-casson-api-user:latest

after_success:
  - echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push cassonchris/udagram-casson-api-feed
  - docker push cassonchris/udagram-casson-api-user