apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-casson-reverse-proxy
  name: udagram-casson-reverse-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-casson-reverse-proxy
  type: LoadBalancer  